---
title: Rainbow message
hero_image: images/banner.png
description: Create a personalised, rainbow coloured greeting.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Create a palette
  - title: Display characters
    completion: engaged
  - title: Scroll a message
    completion: internal
  - title: Reflection
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: What next?
